//
// File generated by rootcint at Wed Sep 21 18:45:03 2022

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NoticeNKFADC500ROOTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NoticeNKFADC500ROOTDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void NKNKFADC500_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NKNKFADC500(void *p = 0);
   static void *newArray_NKNKFADC500(Long_t size, void *p);
   static void delete_NKNKFADC500(void *p);
   static void deleteArray_NKNKFADC500(void *p);
   static void destruct_NKNKFADC500(void *p);
   static void streamer_NKNKFADC500(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::NKNKFADC500*)
   {
      ::NKNKFADC500 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NKNKFADC500 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NKNKFADC500", ::NKNKFADC500::Class_Version(), "./NoticeNKFADC500ROOT.h", 8,
                  typeid(::NKNKFADC500), ::ROOT::DefineBehavior(ptr, ptr),
                  &::NKNKFADC500::Dictionary, isa_proxy, 2,
                  sizeof(::NKNKFADC500) );
      instance.SetNew(&new_NKNKFADC500);
      instance.SetNewArray(&newArray_NKNKFADC500);
      instance.SetDelete(&delete_NKNKFADC500);
      instance.SetDeleteArray(&deleteArray_NKNKFADC500);
      instance.SetDestructor(&destruct_NKNKFADC500);
      instance.SetStreamerFunc(&streamer_NKNKFADC500);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::NKNKFADC500*)
   {
      return GenerateInitInstanceLocal((::NKNKFADC500*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NKNKFADC500*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr NKNKFADC500::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *NKNKFADC500::Class_Name()
{
   return "NKNKFADC500";
}

//______________________________________________________________________________
const char *NKNKFADC500::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKNKFADC500*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NKNKFADC500::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKNKFADC500*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NKNKFADC500::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKNKFADC500*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NKNKFADC500::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKNKFADC500*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void NKNKFADC500::Streamer(TBuffer &R__b)
{
   // Stream an object of class NKNKFADC500.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void NKNKFADC500::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NKNKFADC500.
      TClass *R__cl = ::NKNKFADC500::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_NKNKFADC500(void *p) {
      return  p ? new(p) ::NKNKFADC500 : new ::NKNKFADC500;
   }
   static void *newArray_NKNKFADC500(Long_t nElements, void *p) {
      return p ? new(p) ::NKNKFADC500[nElements] : new ::NKNKFADC500[nElements];
   }
   // Wrapper around operator delete
   static void delete_NKNKFADC500(void *p) {
      delete ((::NKNKFADC500*)p);
   }
   static void deleteArray_NKNKFADC500(void *p) {
      delete [] ((::NKNKFADC500*)p);
   }
   static void destruct_NKNKFADC500(void *p) {
      typedef ::NKNKFADC500 current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_NKNKFADC500(TBuffer &buf, void *obj) {
      ((::NKNKFADC500*)obj)->::NKNKFADC500::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::NKNKFADC500

/********************************************************
* NoticeNKFADC500ROOTDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNoticeNKFADC500ROOTDict();

extern "C" void G__set_cpp_environmentNoticeNKFADC500ROOTDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NoticeNKFADC500ROOT.h");
  G__cpp_reset_tagtableNoticeNKFADC500ROOTDict();
}
#include <new>
extern "C" int G__cpp_dllrevNoticeNKFADC500ROOTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NKNKFADC500 */
static int G__NoticeNKFADC500ROOTDict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKNKFADC500* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKNKFADC500[n];
     } else {
       p = new((void*) gvp) NKNKFADC500[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKNKFADC500;
     } else {
       p = new((void*) gvp) NKNKFADC500;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500open((int) G__int(libp->para[0]), (libusb_context*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500close((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500reset((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500resetTIMER((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500start((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500stop((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_RUN((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_CW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_CW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_RL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_RL((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_DRAMON((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_DRAMON((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_DACOFF((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_DACOFF((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500measure_PED((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PED((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_DLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_DLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_POL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_POL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_PSW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PSW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_AMODE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_AMODE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_PCT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PCT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_PCI((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PCI((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_PWT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PWT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_DT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_DT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_BCOUNT((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_PTRIG((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PTRIG((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500send_TRIG((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_TRIGENABLE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_TRIGENABLE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_TM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_TM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_TLT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_TLT((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_ZEROSUP((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_ZEROSUP((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500send_ADCRST((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500send_ADCCAL((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_ADCDLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_ADCALIGN((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_ADCSTAT((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_PSCALE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_PSCALE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_DSR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_DSR((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_DATA((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500_ADCALIGN_500((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500_ADCALIGN_DRAM((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500flush_DATA((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_EVENT_NUMBER((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->NKFADC500write_ACQUISITION_TIME((int) G__int(libp->para[0]), (unsigned long long) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((NKNKFADC500*) G__getstructoffset())->NKFADC500read_LIVETIME((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NKNKFADC500::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKNKFADC500::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NKNKFADC500::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NKNKFADC500::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNKFADC500*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKNKFADC500::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKNKFADC500::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKNKFADC500::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeNKFADC500ROOTDict_169_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKNKFADC500::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NoticeNKFADC500ROOTDict_169_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NKNKFADC500* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NKNKFADC500(*(NKNKFADC500*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NKNKFADC500 G__TNKNKFADC500;
static int G__NoticeNKFADC500ROOTDict_169_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NKNKFADC500*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NKNKFADC500*) (soff+(sizeof(NKNKFADC500)*i)))->~G__TNKNKFADC500();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NKNKFADC500*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NKNKFADC500*) (soff))->~G__TNKNKFADC500();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NoticeNKFADC500ROOTDict_169_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKNKFADC500* dest = (NKNKFADC500*) G__getstructoffset();
   *dest = *(NKNKFADC500*) libp->para[0].ref;
   const NKNKFADC500& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NKNKFADC500 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNoticeNKFADC500ROOTDict {
 public:
  G__Sizep2memfuncNoticeNKFADC500ROOTDict(): p(&G__Sizep2memfuncNoticeNKFADC500ROOTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNoticeNKFADC500ROOTDict::*p)();
};

size_t G__get_sizep2memfuncNoticeNKFADC500ROOTDict()
{
  G__Sizep2memfuncNoticeNKFADC500ROOTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNoticeNKFADC500ROOTDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500))) {
     NKNKFADC500 *G__Lderived;
     G__Lderived=(NKNKFADC500*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500),G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNoticeNKFADC500ROOTDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NKNKFADC500 */
static void G__setup_memvarNKNKFADC500(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500));
   { NKNKFADC500 *p; p=(NKNKFADC500*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNoticeNKFADC500ROOTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNKNKFADC500(void) {
   /* NKNKFADC500 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500));
   G__memfunc_setup("NKNKFADC500",725,G__NoticeNKFADC500ROOTDict_169_0_1, 105, G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500open",1006,G__NoticeNKFADC500ROOTDict_169_0_2, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid U 'libusb_context' - 0 - ctx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500close",1106,G__NoticeNKFADC500ROOTDict_169_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500reset",1119,G__NoticeNKFADC500ROOTDict_169_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500resetTIMER",1504,G__NoticeNKFADC500ROOTDict_169_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500start",1130,G__NoticeNKFADC500ROOTDict_169_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500stop",1026,G__NoticeNKFADC500ROOTDict_169_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_RUN",1324,G__NoticeNKFADC500ROOTDict_169_0_8, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_CW",1376,G__NoticeNKFADC500ROOTDict_169_0_9, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_CW",1233,G__NoticeNKFADC500ROOTDict_169_0_10, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_RL",1380,G__NoticeNKFADC500ROOTDict_169_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_RL",1237,G__NoticeNKFADC500ROOTDict_169_0_12, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_DRAMON",1671,G__NoticeNKFADC500ROOTDict_169_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_DRAMON",1528,G__NoticeNKFADC500ROOTDict_169_0_14, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_DACOFF",1641,G__NoticeNKFADC500ROOTDict_169_0_15, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_DACOFF",1498,G__NoticeNKFADC500ROOTDict_169_0_16, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500measure_PED",1638,G__NoticeNKFADC500ROOTDict_169_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PED",1296,G__NoticeNKFADC500ROOTDict_169_0_18, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_DLY",1455,G__NoticeNKFADC500ROOTDict_169_0_19, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_DLY",1312,G__NoticeNKFADC500ROOTDict_169_0_20, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_THR",1460,G__NoticeNKFADC500ROOTDict_169_0_21, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_THR",1317,G__NoticeNKFADC500ROOTDict_169_0_22, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_POL",1457,G__NoticeNKFADC500ROOTDict_169_0_23, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_POL",1314,G__NoticeNKFADC500ROOTDict_169_0_24, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_PSW",1472,G__NoticeNKFADC500ROOTDict_169_0_25, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PSW",1329,G__NoticeNKFADC500ROOTDict_169_0_26, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_AMODE",1580,G__NoticeNKFADC500ROOTDict_169_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_AMODE",1437,G__NoticeNKFADC500ROOTDict_169_0_28, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_PCT",1453,G__NoticeNKFADC500ROOTDict_169_0_29, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PCT",1310,G__NoticeNKFADC500ROOTDict_169_0_30, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_PCI",1442,G__NoticeNKFADC500ROOTDict_169_0_31, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PCI",1299,G__NoticeNKFADC500ROOTDict_169_0_32, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_PWT",1473,G__NoticeNKFADC500ROOTDict_169_0_33, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PWT",1330,G__NoticeNKFADC500ROOTDict_169_0_34, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_DT",1374,G__NoticeNKFADC500ROOTDict_169_0_35, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_DT",1231,G__NoticeNKFADC500ROOTDict_169_0_36, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_BCOUNT",1538,G__NoticeNKFADC500ROOTDict_169_0_37, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_PTRIG",1612,G__NoticeNKFADC500ROOTDict_169_0_38, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PTRIG",1469,G__NoticeNKFADC500ROOTDict_169_0_39, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500send_TRIG",1403,G__NoticeNKFADC500ROOTDict_169_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_TRIGENABLE",1955,G__NoticeNKFADC500ROOTDict_169_0_41, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_TRIGENABLE",1812,G__NoticeNKFADC500ROOTDict_169_0_42, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_TM",1383,G__NoticeNKFADC500ROOTDict_169_0_43, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_TM",1240,G__NoticeNKFADC500ROOTDict_169_0_44, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_TLT",1466,G__NoticeNKFADC500ROOTDict_169_0_45, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_TLT",1323,G__NoticeNKFADC500ROOTDict_169_0_46, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_ZEROSUP",1790,G__NoticeNKFADC500ROOTDict_169_0_47, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_ZEROSUP",1647,G__NoticeNKFADC500ROOTDict_169_0_48, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500send_ADCRST",1542,G__NoticeNKFADC500ROOTDict_169_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500send_ADCCAL",1501,G__NoticeNKFADC500ROOTDict_169_0_50, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_ADCDLY",1655,G__NoticeNKFADC500ROOTDict_169_0_51, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_ADCALIGN",1785,G__NoticeNKFADC500ROOTDict_169_0_52, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_ADCSTAT",1595,G__NoticeNKFADC500ROOTDict_169_0_53, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_PSCALE",1662,G__NoticeNKFADC500ROOTDict_169_0_54, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_PSCALE",1519,G__NoticeNKFADC500ROOTDict_169_0_55, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_DSR",1455,G__NoticeNKFADC500ROOTDict_169_0_56, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_DSR",1312,G__NoticeNKFADC500ROOTDict_169_0_57, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_DATA",1361,G__NoticeNKFADC500ROOTDict_169_0_58, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid i - - 0 - bcount "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500_ADCALIGN_500",1474,G__NoticeNKFADC500ROOTDict_169_0_59, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500_ADCALIGN_DRAM",1617,G__NoticeNKFADC500ROOTDict_169_0_60, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500flush_DATA",1495,G__NoticeNKFADC500ROOTDict_169_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_EVENT_NUMBER",2017,G__NoticeNKFADC500ROOTDict_169_0_62, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500write_ACQUISITION_TIME",2461,G__NoticeNKFADC500ROOTDict_169_0_63, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid m - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NKFADC500read_LIVETIME",1686,G__NoticeNKFADC500ROOTDict_169_0_64, 109, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__NoticeNKFADC500ROOTDict_169_0_65, 85, G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NKNKFADC500::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__NoticeNKFADC500ROOTDict_169_0_66, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKNKFADC500::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__NoticeNKFADC500ROOTDict_169_0_67, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NKNKFADC500::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__NoticeNKFADC500ROOTDict_169_0_68, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NKNKFADC500::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NoticeNKFADC500ROOTDict_169_0_72, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NoticeNKFADC500ROOTDict_169_0_73, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKNKFADC500::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NoticeNKFADC500ROOTDict_169_0_74, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKNKFADC500::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__NoticeNKFADC500ROOTDict_169_0_75, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKNKFADC500::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NoticeNKFADC500ROOTDict_169_0_76, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKNKFADC500::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NKNKFADC500", 725, G__NoticeNKFADC500ROOTDict_169_0_77, (int) ('i'), G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500), -1, 0, 1, 1, 1, 0, "u 'NKNKFADC500' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NKNKFADC500", 851, G__NoticeNKFADC500ROOTDict_169_0_78, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__NoticeNKFADC500ROOTDict_169_0_79, (int) ('u'), G__get_linked_tagnum(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500), -1, 1, 1, 1, 1, 0, "u 'NKNKFADC500' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNoticeNKFADC500ROOTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNoticeNKFADC500ROOTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNoticeNKFADC500ROOTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_libusb_context = { "libusb_context" , 115 , -1 };
G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_NKNKFADC500 = { "NKNKFADC500" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNoticeNKFADC500ROOTDict() {
  G__NoticeNKFADC500ROOTDictLN_TClass.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_TBuffer.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_TMemberInspector.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_TObject.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_libusb_context.tagnum = -1 ;
  G__NoticeNKFADC500ROOTDictLN_NKNKFADC500.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNoticeNKFADC500ROOTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_libusb_context);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NoticeNKFADC500ROOTDictLN_NKNKFADC500),sizeof(NKNKFADC500),-1,161024,"NKNKFADC500 wrapper class for root",G__setup_memvarNKNKFADC500,G__setup_memfuncNKNKFADC500);
}
extern "C" void G__cpp_setupNoticeNKFADC500ROOTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNoticeNKFADC500ROOTDict()");
  G__set_cpp_environmentNoticeNKFADC500ROOTDict();
  G__cpp_setup_tagtableNoticeNKFADC500ROOTDict();

  G__cpp_setup_inheritanceNoticeNKFADC500ROOTDict();

  G__cpp_setup_typetableNoticeNKFADC500ROOTDict();

  G__cpp_setup_memvarNoticeNKFADC500ROOTDict();

  G__cpp_setup_memfuncNoticeNKFADC500ROOTDict();
  G__cpp_setup_globalNoticeNKFADC500ROOTDict();
  G__cpp_setup_funcNoticeNKFADC500ROOTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNoticeNKFADC500ROOTDict();
  return;
}
class G__cpp_setup_initNoticeNKFADC500ROOTDict {
  public:
    G__cpp_setup_initNoticeNKFADC500ROOTDict() { G__add_setup_func("NoticeNKFADC500ROOTDict",(G__incsetup)(&G__cpp_setupNoticeNKFADC500ROOTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNoticeNKFADC500ROOTDict() { G__remove_setup_func("NoticeNKFADC500ROOTDict"); }
};
G__cpp_setup_initNoticeNKFADC500ROOTDict G__cpp_setup_initializerNoticeNKFADC500ROOTDict;

