/********************************************************************
* NoticeNKFADC500ROOTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NoticeNKFADC500ROOTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNoticeNKFADC500ROOTDict();
extern void G__cpp_setup_inheritanceNoticeNKFADC500ROOTDict();
extern void G__cpp_setup_typetableNoticeNKFADC500ROOTDict();
extern void G__cpp_setup_memvarNoticeNKFADC500ROOTDict();
extern void G__cpp_setup_globalNoticeNKFADC500ROOTDict();
extern void G__cpp_setup_memfuncNoticeNKFADC500ROOTDict();
extern void G__cpp_setup_funcNoticeNKFADC500ROOTDict();
extern void G__set_cpp_environmentNoticeNKFADC500ROOTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NoticeNKFADC500ROOT.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TClass;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TBuffer;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TMemberInspector;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_TObject;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_libusb_context;
extern G__linked_taginfo G__NoticeNKFADC500ROOTDictLN_NKNKFADC500;

/* STUB derived class for protected member access */
